
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aba_network_development

test:
  <<: *default
  database: aba_network_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  
production:
  <<: *default
  database: dbaba
  username: dbaba_user
  password: <%= ENV["ABA_NETWORK_DATABASE_PASSWORD"] %>
  
